version: '3'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    ports:
      - 6006:6006
    networks:
      - app_network

networks:
  app_network:
    external: true
