lexik_jwt_authentication:
    api_platform:
        check_path: /authentication
        username_path: login
        password_path: password
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
