on:
  push:
    tags:
      - '*'
name: Publish release on Sentry
jobs:
  deploy:
    if: ${{ !github.event.act }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Silent for test
    #   - uses: actions/checkout@v3
    #   - name: Sentry Release
    #     uses: getsentry/action-release@v1
    #     env:
    #       SENTRY_URL: ${{ secrets.SENTRY_URL }}
    #       SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #       SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    #       SENTRY_PROJECT: agents-en-intervention
    #     with:
    #       environment: prod
    #       version: ${{ github.ref }}
